### ISSUE TITLE
Reduce amount of popup-windows

### ISSUE THREAD

**Issue by stveit** [geteduroam/windows-app#12]
Currently when trying to download a config file for a profile after choosing either a profile or an institution with only one profile, a messagebox pop ups. Might be prettier/better to have the message show up inside the window/page itself

**Comment by pbsds** [comment]
Exception messages should be shown in the ui as a separate page

**Comment by stveit** [comment]
<img width="439" alt="github-issue" src="https://user-images.githubusercontent.com/31960753/89990919-5732e080-dc83-11ea-891c-deb6bfb1ca6d.png">
example

**Comment by jornane** [comment]
Exception messages can still be separate windows. I think it's better to have them as separate windows even since they indicate that something is out of the ordinary.

What we definitely needed to get rid of was multiple dialog windows after each other. After closing a dialog window (no matter how) you must be back in the application. We're here now, so closing this issue.
